version: 2
formats: all

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

python:
  install:
    # # for docs building, not the actual dependencies of the lib
    # - requirements: docs/requirements.txt

    # # # now for the actual dependencies to install themselves before generating docs
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
