name: Build

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build_and_release:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: python -m pip install setuptools==73.0.1 build==1.2.1

      - name: Build wheels
        run: python -m build # on ./dist
        env:
          CIBW_TEST_COMMAND: "python -m unittest src.tests"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --generate-notes

      - name: Upload artifacts to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >
          gh release upload
          '${{ github.ref_name }}' dist/**
          --repo '${{ github.repository }}'